micronaut:
  application:
    name: calibrateApi
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres?preparedStatementCacheQuries=0
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    db-type: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    auto-commit: true
    maximum-pool-size: 50
    minimum-idle: 2
    idle-timeout: 600000
    data-source-properties:
      reWriteBatchInserts: true
      disableColumnSanitiser: true
netty:
  default:
    allocator:
      max-order: 3
